language: php
php:
- '5.6'
- '7.0'
- hhvm
before_script:
- cp .env.travis .env
- mysql -e 'create database myjob_test;'
- composer self-update
- composer install --prefer-source --no-interaction --dev
- php artisan key:generate
- php artisan migrate:refresh --seed
script: phpunit
matrix:
  fast_finish: true
notifications:
  slack:
    secure: 02gSd5H7wJyDySK2s71YzcMVHeI4B4Ta7OeyQDMMAKzTBHPWiFhlj3dxF/PR7+Lou8nhiklZ+b+hajEYtmjIOgWTBMKec0uQn9AP3sTKw3/ogiErzIXQHhCV7NxCyCg1MHfrZEih3ZWEYeu2oVtIk/9T5Acsm9isT4rakH9Qqr4PsSG1NOuSj7aSm/+/x2gu3Vj7OrsDCctLVDGwSQ+q095iHWcFoZ9d3j5920Y4HeaKfRQMOqqeG3XHh8KBtlGN6x2+VsbpvXIUAnG70p5PBE6oKWi/MfZwTYmJP2r8ORf8sjiolNled+9YNq7Gunf7CbyQmlr8/IEmEfGu7ZkAzORi7IuSvVaprjj3sMNYZpHAJ3R/fDXhJrm9/o+/qYorsm6sZj0MhOe0LESNf5dv/4qIhYMqvCult78uow4jaKcxHIhQVDaZMmxoGfcRWZY7Hca8m0LNz2S2Wy8v+8QbL8ar0+Hn4/A/E+aZ0RTcdwmFOEoT5FCNFPf7R7+q1AckoNzexLhSlAZBTL5w04Oimzrd21/rYb+LOfeBdyiD/j/I9GABdY6NaEST306eG67paa/G69i6PibH5lYROFp6fFYSH/gRtFyvsR3fom5HKyl0vB5jHnQ9TX+lk/eOt4aYea6mUreNSuOUiqHiz8ADf/XF37YqeibxbSjrcCijBKg=
